Doch.Web/Models/ErrorViewModel.cs
namespace Doch.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Doch.Web/Controllers/DochController.cs
using Doch.Models;
using Doch.Web.Code;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Doch.Models.Exceptions;

namespace Doch.Web.Controllers
{
    [Controller]
    public class DochController : Controller
    {
        private readonly IApiClient _apiClient;
        public DochController(IApiClient client) 
        {
            _apiClient = client;
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<Employee>>> Index()
        {
            ViewData["Title"] = "Dochadzka";
            ViewData["APIBaseUrl"] = _apiClient.APIBaseUrl;
            try
            {
                IEnumerable<Employee> workHours = await _apiClient.GetEmployeeList();
                return View(workHours);
            }
            catch (DataException ex)
            {
                TempData["error"] = ex.Message;
                return BadRequest();
            }
        }
        [HttpGet("{id}")]
        public async Task<ActionResult> Detail(int id)
        {
            // TODO: https://www.youtube.com/watch?v=gRBC50ddQzw
            var employee = await _apiClient.GetEmployee(id);
            if (employee == null) return NotFound();

            return View(employee);
        }

        [HttpGet("create")]
        public ActionResult<Employee> Create()
        {
            ViewData["Title"] = "Create new Employee";
            ViewData["APIBaseUrl"] = _apiClient.APIBaseUrl;
            return View(new Employee());
        }
        [HttpPost("create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Employee employee)
        {
            int employeeId;
            try
            {
                if (ModelState.IsValid)
                {
                    employee.IpCountryCode = await _apiClient.GetCoutryByIP(employee.IpAddress);
                    employeeId = await _apiClient.CreateEmployee(employee);
                    if (employeeId != 0)
                    {
                        TempData["success"] = $"Employee {employee.Name} {employee.SurName} created.";
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (DataException ex)
            {
                Utils.ParseRequestException(ex, ModelState);
            }

            return View(employee);
        }

        [HttpGet("Edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                Employee? employee = await _apiClient.GetEmployee(id);
                return employee == null ? NotFound() : View(employee);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        [HttpPost("edit/{id}")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(Employee employee)
        {
            int employeeId;
            try
            {
                if (ModelState.IsValid)
                {
                    employee.IpCountryCode = await _apiClient.GetCoutryByIP(employee.IpAddress);
                    employeeId = await _apiClient.UpdateEmployee(employee);
                    if (employeeId != 0)
                    {
                        TempData["success"] = $"Employee {employee.Name} {employee.SurName} updated.";
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (DataException ex)
            {
                Utils.ParseRequestException(ex, ModelState);
                return View(employee);
            }

            return View(employee);
        }



    }
}

Doch.Web/Views/Doch/Create.cshtml
@using Doch.Models  
@model Employee
<form method="post">
    <div class="border p-3 mt-4">
        <div class="rov pb-2">
            <h2 class="text-primary">Create Employee</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All" class="alert-danger"></div>*@
        <div class="col-sm-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" autofocus />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col-sm-3">
            <label asp-for="SurName"></label>
            <input asp-for="SurName" class="form-control" />
            <span asp-validation-for="SurName" class="text-danger"></span>
        </div>
        <div class="col-sm-3">
            <label asp-for="BirthDate"></label>
            <input asp-for="BirthDate" class="form-control" />
            <span asp-validation-for="BirthDate" class="text-danger"></span>
        </div>
        <div class="col-sm-3">
            <label asp-for="PositionId"></label>
            <select asp-for="PositionId" 
             asp-items="(Doch.Web.Code.Utils.GetPositions().Result.Select(p => new SelectListItem() { Value = p.Key, Text = p.Value})).ToList()" 
             class="form-select">
                <option value="">--- Select position ---</option>
            </select>
            <span asp-validation-for="PositionId" class="text-danger"></span>
        </div>
        <div class="col-sm-3">
            <label asp-for="IpAddress"></label>
            <input asp-for="IpAddress" class="form-control" />
            <span asp-validation-for="IpAddress" class="text-danger"></span>
        </div>
        <div class="col-lg-12 visually-hidden">
            <label asp-for="IpCountryCode"></label>
            <input asp-for="IpCountryCode" class="form-control" value="blank" />
            <span asp-validation-for="IpCountryCode" class="text-danger"></span>
        </div>
        <br />
        <button class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Doch" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

Doch.Web/Views/Doch/Detail.cshtml
@using Doch.Models;
@model Employee


<div class="border p-3 mt-4">
    <div class="rov pb-2">
        <h2 class="text-primary">@Model.Name @Model.SurName</h2>
        <hr />
    </div>
    <div class="col-10">
        <table>
            <thead></thead>
            <tbody>
                <tr>
                    <th>Full Name:</th>
                    <td>@Model.Name @Model.SurName</td>
                </tr>
                <tr>
                    <th>Date of Birth:</th>
                    <td>@Model.BirthDate.ToShortDateString()</td>
                </tr>
                <tr>
                    <th>Position:</th>
                    <td>
                        @if (Model.Position != null)
                            @Model.Position.PositionName



                        </td>
                    </tr>
                    <tr>
                        <th>IP Address:</th>
                        <td>@Model.IpAddress</td>
                    </tr>
                    <tr>
                        <th>IP Country:</th>
                        <td>@Model.IpCountryCode</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <br />
    </div>

Doch.Web/Views/Doch/Edit.cshtml
@using Doch.Models
@model Employee

<form method="post">
    <div class="border p-3 mt-4">
        <div class="rov pb-2">
            <h2 class="text-primary">Edit employee @Model.Name @Model.SurName</h2>
            <hr />
        </div>
        @*<div asp-validation-summary="All" class="alert-danger"></div>*@
        <div>
            <input type="hidden" asp-for="EmployeeId" />
        </div>
        <div class="col-sm-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" autofocus />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="col-sm-3">
            <label asp-for="SurName"></label>
            <input asp-for="SurName" class="form-control" />
            <span asp-validation-for="SurName" class="text-danger"></span>
        </div>
        <div class="col-sm-3">
            <label asp-for="BirthDate"></label>
            <input asp-for="BirthDate" class="form-control" />
            <span asp-validation-for="BirthDate" class="text-danger"></span>
        </div>
        <div class="col-sm-3">
            <label asp-for="PositionId"></label>
            <select asp-for="PositionId"
                    asp-items="(Doch.Web.Code.Utils.GetPositions().Result.Select(p => new SelectListItem() { Value = p.Key, Text = p.Value})).ToList()"
                    class="form-select">
            </select>
            <span asp-validation-for="PositionId" class="text-danger"></span>
        </div>
        <div class="col-sm-3">
            <label asp-for="IpAddress"></label>
            <input asp-for="IpAddress" class="form-control" />
            <span asp-validation-for="IpAddress" class="text-danger"></span>
        </div>
        <div class="col-sm-3 visually-hidden">
            <label asp-for="IpCountryCode"></label>
            <input asp-for="IpCountryCode" class="form-control" value="NON" />
            <span asp-validation-for="IpCountryCode" class="text-danger"></span>
        </div>
        <br />
        <button class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Doch" asp-action="Index" class="btn btn-secondary" style="width:150px">
            Back to List
        </a>
    </div>
</form>

Doch.Web/Views/Doch/Index.cshtml
@using Doch.Models
@model IEnumerable<Employee>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">@ViewData["Title"]</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Doch" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i>&nbsp;Create Employee Item
            </a>
        </div>
    </div>
</div>
<br />
<div style="">
    <table id="dataTable" class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    Full Name
                </th>
                <th class="text-end">
                    Date Of Birth
                </th>
                <th>
                    Position
                </th>
                <th>
                    IP Address
                </th>
                <th class="text-center">
                    IP Country
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr id="@item.EmployeeId">
                    <td>
                        <a asp-controller="Doch" asp-action="Detail" asp-route-id="@item.EmployeeId">
                            @item.Name &nbsp; @item.SurName
                        </a>
                    </td>
                    <td class="text-end">
                        @item.BirthDate.ToShortDateString()
                    </td>
                    <td>
                        @if (item.Position != null)
                            @item.Position.PositionName

                    </td>
                    <td>
                        @item.IpAddress
                    </td>
                        <td class="text-center">
                        @item.IpCountryCode
                    </td>
                    <td class="flex-nowrap">
                        <div class="float-end">
                            <a asp-controller="Doch" asp-action="Edit" asp-route-id="@item.EmployeeId" class="btn btn-primary">
                                <i class="bi bi-pencil-square"></i> Edit
                            </a>
                            &nbsp;
                            <a class="btn btn-danger" onclick="return deleteItem('@ViewData["APIBaseUrl"]', 'Employee', @item.EmployeeId, '@item.Name @item.SurName');">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script type="text/javascript">
function deleteItem(apiBaseUrl, entity, id, name) {
    if (window.confirm('Delete employee '+name+'?'))
    {
        $.ajax({
                url: "".concat(apiBaseUrl, "/api/doch/").concat(id),
            type: "DELETE",
            data: {},
            headers: {
                "Content-Type": "text/xml; charset=utf-8",
                "Accept": "application/json",
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Methods": "POST, GET, PUT, DELETE",
                "Access-Control-Allow-Headers": "Origin, X-Requested-With, Content-Type"
            }
            })
            .done(function () {
                    $("#".concat(id)).remove();
                    alert("Item ".concat(name, " deleted."));
                }).fail(function (data) {
                    var _a;
                    alert((_a = data.responseText) !== null && _a !== void 0 ? _a : "Error delting {entity}.");
            })
    }
}

</script>

Doch.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Doch.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Doch.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Doch" asp-action="Index">Doch.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doch" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Doch.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Doch.Web/Views/Shared/_Notification.cshtml
<script type="text/javascript">
var tOpt={closeButton:!0,debug:!1,newestOnTop:!1,progressBar:!1,positionClass:"toast-top-right",preventDuplicates:!1,onclick:null,showDuration:"2000",hideDuration:"1000",timeOut:"2000",extendedTimeOut:"1000",showEasing:"swing",hideEasing:"linear",showMethod:"fadeIn",hideMethod:"fadeOut"};
</script>

@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]', '', tOpt);
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]', '', tOpt);
    </script>
}
@if (TempData["warning"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.warning('@TempData["warning"]', '', tOpt);
    </script>
}
@if (TempData["info"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.info('@TempData["info"]', '', tOpt);
    </script>
}